### PR TITLE
Store downloaded artifacts in OCI Object Storage

### LINKED ISSUE #122: Store downloaded artifacts in OCI Object Storage
**What would you like to be added**: I would like to store exported Nexus artifacts in [OCI Object Storage](https://www.oracle.com/cloud/storage/object-storage.html)

**Why is this needed**:
Object Storage is a durable storage, you don't need to care about space management and availability.
It can be integrated with other services which may need builds archives (e.g. if you don't want to keep all of them on Nexus)

### PR DESCRIPTION
**Pull request by vsoloviov**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR allows storing Nexus artifacts in [OCI Object Storage](https://www.oracle.com/cloud/storage/object-storage.html) instead of (or within) a local storage.

Also, I've found that this tool re-downloads all artifacts on each run: so I have added md5 checksum comparison, so `backup` skips downloading if file exists and matches md5 sum received from Nexus

**Which issue(s) this PR fixes**:
Fixes #122 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- Adds OCI Object Storage as a remote storage for backups
- Skips download if artifact already exists
```

### CODE REVIEW

**Comment by 030** [comment]
Thank for creating a Pull Request. Could you create an issue as well and could you return the errors from the functions? Please let me know when I can continue reviewing. Currently the PR is in draft mode.

**Comment by vsoloviov** [comment]
Thanks, I'm going to add some tests, I'll set it to `Ready for review` once completed.

**Comment by 030** [comment]
@vsoloviov Could you update your email address in the commits?

**Comment by vsoloviov** [comment]
> @vsoloviov Could you update your email address in the commits?

Sure, done.

**Comment by 030** [comment]
@vsoloviov Thank you.

**Pull request merged**
