### PR TITLE
Add flag "insecureSkipVerify" to skip the repository certificate validation

### PR DESCRIPTION
**Pull request by titou10titou10**
Partially addresses #107

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This adds a global flag "-insecureSkipVerify" to skik the repository certificate validations

**Which issue(s) this PR fixes**:
 Partially #107

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by titou10titou10** [comment]
yw.
I've edited the readme.md file and also added a section called ""Clone" the
content of a repository in a different Nexus 3 server in a different
repository" because this is the use case Imn using n3dr now
You should review it
As for the integration test, I'm afraid I will not be abale to work on that
soon. Could you do it?
Thx

Le mer. 15 janv. 2020 à 11:11, Ben van B <notifications@github.com> a
écrit :

**Comment by 030** [comment]
@titou10titou10 thanks for the PR. I assume you tested this in conjunction with a nexus3 that contains self signed certificates. I will create an issue for adding an integration test in the future.

**Comment by 030** [comment]
@titou10titou10 could you try the 3.3.4-rc1 release?

**Comment by titou10titou10** [comment]
- Yes my change has been tested with a nexus3 that is assigned a certificate signed by our own corporate certificate authority, which is an equivalent of self-signed certificate.
- v3.3.4-rc1 works
- I will close issue #107 and open another one as we are now able to bypass certificate validation but it would be more secure to have a way to tell n3dr what CA certificate to use when accessing a nexus3 server instead of bypassing the validation. This would be an enhancement

**Comment by titou10titou10** [comment]
BTW the`README.md`file  should be updated in the "installation" section, with the current version, or replace `.../download/3.1.1/...`by`../download/x.y.z/...`to keep it generic
The first time I install the tool, I install v3.1.1 without checking earlier versions..

..and thanks for having developped this tool!

**Pull request merged**
